### ISSUE TITLE
Create a page about state operations

### ISSUE THREAD

**Issue by RafaelReia** [bschaatsbergen/terraformbyexample#36]
Create a page with examples on how to manage terraform state by providing examples to the following commands

- terraform state rm
- terraform state list
- terraform import
- terraform show

What do you think?

**Comment by bschaatsbergen** [comment]
This can come in very handy, perhaps we can categorize these under pages like `State` and address them in an as minimal as possible way? What do you think?

**Comment by RafaelReia** [comment]
Just to clarify do you mean 1 page named `State` where we define those operations or multiple pages? 

I like the approach of addressing them in a minimal way

**Comment by bschaatsbergen** [comment]
Hmm I'll have to think this through properly but I'm thinking about a singular page that explains 'State' in a nutshell (somewhere after the hello world) and references these 'state mv' commands etc.

What do you think?

**Comment by RafaelReia** [comment]
Sounds good, I'll send a PR in the following days
